//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace DriveServiceLibrary
{
    using System;
    using System.Collections.Generic;


    [DataContract]    
    public class Users
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Login { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Surname { get; set; }
        [DataMember]
        public Nullable<int> Age { get; set; }
        [DataMember]
        public byte[] Image { get; set; }
        [DataMember]
        public int Access_level_ID { get; set; }

       
        public virtual Access_level Access_level { get; set; }
    }
}
